ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

baseurl = "https://maraaverick.rbind.io/"
relativeurls = true
languageCode = "en-us"
title = "Mara Averick"

# Enable emoji
enableEmoji = true

# Enable comments by entering your Disqus shortname
disqusShortname = "maraaverick"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-101515030-1"

# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
footnoteanchorprefix = "°"

theme = "hugo-icarus-theme"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."


[permalinks]
    post = "/:year/:month/:slug"


[params]
    # Tell me who you are
    author = "Mara Averick"
    bio = "data nerd at large"
    location = ""
    site_description = ""
    copyright  = "Mara Averick. Powered by [Hugo](//gohugo.io). Theme by [PPOffice](https://github.com/ppoffice)."
    avatar = "img/mga_profile_pic.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = ""
    logo = "img/02.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["css/tomorrow-night-bright.css"]
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label = "Roundups"
    link = "/tags/roundups/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/dataandme"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    twitter         = "dataandme"
    github          = "batpigandme"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    medium          = "dataandme"
    wordpress       = ""
    tumblr          = ""
    linkedin        = "maraaverick"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = "dataandme"
    goodreads       = "batpigandme"

# options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "tomorrow-night-bright"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = false
    tags = false
    tag_cloud = false

# Add algolia
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags", "description"]

# Add outputs
[outputs]
home = ["html", "rss", "Algolia"]
